# Site
repository: anthonymbah1/anthonymbah1.github.io
# favicon: assets/img/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anthony Mbah
title: Data Scientist | AI/ML Enthusiast | MSIS Graduate
email: mbahanthony67@gmail.com
# email_title: Email
phone:
# phone_title: Phone
website: https://anthonymbah1.github.io
# website_title: Website

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username: anthonymbah1
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: tony-mbah
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
additional_links:
- title: GitHub
  icon: fab fa-github
  url: https://github.com/anthonymbah1
- title: LinkedIn
  icon: fab fa-linkedin
  url: https://www.linkedin.com/in/tony-mbah

# About Section
# about_title: About Me
about_profile_image: /assets/img/profile.jpg
about_content: |
  A highly motivated graduate with a Master's in Information Systems (Big Data Analytics focus) and practical experience in building and managing infrastructure and deployment pipelines.

  My background combines a strong academic foundation with hands-on experience in DevOps principles and applied data science techniques, including advanced NLP and machine learning model development.

  I'm genuinely excited by the rapid evolution of technology and am passionate about being at the forefront of groundbreaking advancements like Agentic AI and other transformative technologies shaping our world.

  Eager to contribute to innovative Data Science and AI/ML initiatives.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Patent Topic Modeling with ETM and BERT
        quote: Explored advanced topic modeling using ETM and contextual embeddings.
        description: |
          Explored topic modeling using ETM with both GloVe and learned embeddings on patent abstracts from PatentsView.
          Evaluated the feasibility of integrating BERT's contextual embeddings into ETM.
          Evaluated BERTopic with and without seed words; compared GPU-based vs CPU-based execution performance on Colab.

      - layout: left
        title: Amazon Product Review Sentiment Classifier
        quote: Fine-tuned BERT to classify sentiment in customer reviews.
        description: |
          Built a transformer-based sentiment analysis pipeline using BERT, fine-tuning it to classify reviews as Positive, Neutral, or Negative.
          Implemented class-weighting and oversampling to combat class imbalance.
          Achieved 66.5% accuracy and 80.4% recall on the negative class.

      - layout: left
        title: GenAI Symptom Checker with RAG Architecture
        quote: Developed an emergency triage system using Retrieval-Augmented Generation.
        description: |
          Built a GenAI-powered triage system combining OpenAI LLM, Pinecone semantic search, and LangChain.
          Used SciSpaCy, NLTK, and SQLite to manage patient records.
          Achieved 100% recall in emergency cases with 75–80% overall accuracy.

      - layout: left
        title: Deepfake Detection System – Multi-modal (Text/Image/Video)
        quote: Designed a scalable system to detect deepfakes across three data types.
        description: |
          Integrated ViT for image analysis, ResNeXt with LSTM for video, and fine-tuned BERT for text.
          Used AWS Glue, S3, and Athena for data handling and deployed using Docker.
          Achieved >96% image F1-score with Grad-CAM visualizations for interpretability.

      - layout: left
        title: Privacy-First RAG System for Mental Health Support
        quote: Built a secure GenAI chatbot for sensitive data interactions.
        description: |
          Created a privacy-focused RAG chatbot with SQLite-based data security.
          Implemented prompt filtering, token redaction, and role-based access control.
          Included regex-based injection protection and identity verification.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Georgia State University
        sub_title: Graduate Research Assistant
        caption: Aug 2024 – Present
        quote: Worked on advanced NLP and AI models for patent analysis.
        description: |
          Implemented an Embedding Topic Model (ETM) using BERT and GloVe/Word2Vec on 50,000+ patent abstracts.
          Improved topic coherence by 38% with BERT over traditional embeddings.
          Provided insights into IP strategy through gap analysis and interpretability methods.

      - layout: right
        title: DevOps Bootcamp Experience
        sub_title: DevOps Trainee / Project Work
        caption: 2023
        quote: Completed 8-month DevOps bootcamp with real-world infrastructure simulations.
        description: |
          Built automated CI/CD pipelines using tools like Jenkins, CodePipeline, and Docker.
          Configured and maintained Kubernetes clusters and AWS infrastructure (EC2, VPC, IAM, etc.).
          Provisioned cloud environments with Terraform and Ansible. Monitored and scaled infrastructure using CloudWatch and Prometheus.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Georgia State University, J. Mack Robinson College of Business
        sub_title: M.S. in Computer Information Systems (Big Data Analytics)
        caption: Aug 2024 – July 2025
        quote: Graduate coursework and research in Big Data and Generative AI
        description: |
          Relevant Courses: Big Data Infrastructure, Big Data Analytics Experience, Data Programming, Generative AI

      - layout: top-right
        title: Rutgers University, Rutgers Business School
        sub_title: B.S. in Management Information Systems
        caption: Sept 2019 – May 2023
        quote: Undergraduate degree combining business and tech foundations
        description: |
          Graduated with strong coursework in IT systems, business analytics, and systems design.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of my academic and technical pursuits, I’m a big fan of staying active, exploring new recipes in the kitchen, playing video games, and watching Formula 1 races. I believe in balance — working hard and playing smart.

# Footer
footer_show_references: true
# references_title: References on request

# Build settings
# remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
